name: rapids
channels:
- rapidsai
- rapidsai-nightly
- conda-forge
- nvidia
- pytorch
dependencies:
- cudatoolkit=CUDA_VER
- cudf=RAPIDS_VER
- dask-cudf=RAPIDS_VER
- dask-cuda=RAPIDS_VER
- numpy>=NUMPY_VER
- cupy
- pynvml
- pytorch=*=*cudaCUDA_VER*
- ucx-proc=*=gpu
- ucx-py=UCX_PY_VER
